### ISSUE TITLE
Remove default x-v values in Register request header parameters

### ISSUE THREAD

**Issue by nils-work** [ConsumerDataStandardsAustralia/standards-staging#293]
**Description**
Remove the following `"default"` values from the Register [spec.](https://consumerdatastandardsaustralia.github.io/standards/includes/swagger/cds_register.json) so the **Non-normative Examples** shows these values only as `'string'`.

Five instances with `"1"`:
``` diff
          "in" : "header",
          "name" : "x-v",
          "required" : false,
          "schema" : {
-           "default" : "1",
            "type" : "string"
          },
```
![image](https://github.com/ConsumerDataStandardsAustralia/standards-staging/assets/60594671/8189520d-bd98-4899-8548-08d4119d2192)

One instance with `"2"`:
``` diff
          "in" : "header",
          "name" : "x-v",
          "required" : false,
          "schema" : {
-           "default" : "2",
            "type" : "string"
          },

```
![image](https://github.com/ConsumerDataStandardsAustralia/standards-staging/assets/60594671/ca6f8586-4ba0-49a8-bb49-a3fcbe08019d)

**Comment by perlboy** [comment]
Doesn't align with the currently documented Standards @nils-work:
<img width="749" alt="image" src="https://github.com/ConsumerDataStandardsAustralia/standards-staging/assets/4291448/3e593acf-7a35-4dc5-bd93-26f8e8c22212">

Also, there is _no default_ once it becomes a mandatory header.

**Comment by nils-work** [comment]
Thanks @perlboy 

I was thinking that the removal of the defaults at the end of this Maintenance Iteration could roughly align to the header becoming mandatory as per the [published dates](https://consumerdataright.atlassian.net/wiki/spaces/DP/pages/30081043/Delivery+Dates) for Register API changes, but we could defer this change beyond then. Would that be the preference?

I've just noticed though, that the default should probably stay for [Get Data Holder Statuses](https://consumerdatastandardsaustralia.github.io/standards/index.html?examples#get-data-holder-statuses) as only v1 exists for that endpoint and it could be expected to continue to default to x-v: 1.

**Comment by biza-io** [comment]
"Roughly" aligning the published and binding specification is a pretty terrible precedent to set. ACCC should give a concrete date on when it must happen by and align with FDOs rather than acting like they can do whatever they want. To be honest I'd probably go down the path of removing the default and making `x-v` mandatory across the board now that people have been given sufficient time to prepare but no doubt some ego driven inconsistency will kick in. 🤷

**Comment by perlboy** [comment]
Apologies, switched to individual account.

"Roughly" aligning the published and binding specification is a pretty terrible precedent to set. ACCC should give a concrete date on when it must happen by and align with FDOs rather than acting like they can do whatever they want. To be honest I'd probably go down the path of removing the default and making `x-v` mandatory across the board now that people have been given sufficient time to prepare but no doubt some ego driven inconsistency will kick in. 🤷

**Comment by JamesMBligh** [comment]
When we went live the date of decommissioning was unknown.  At the time it was suggested that the older versions would be decommissioned in April of this year.

As there was no concrete date we decided to leave it optional with a default value.  Once the default versions are decommissioned we can then update the standards to make the fields mandatory as, at that point, it will be correct in practice.  A failure to provide x-v from them will result in an error.  The error code might be incorrect for a while (unsupported version instead of missing header) but it will still be an error and the error code will catch up.

**Comment by JamesMBligh** [comment]
In the MI meeting today the ACCC told us that they would likely deprecate old versions soon and post in the holistic thread for MI16.

We can therefore make this change when we do the MI16 release along with making the x-v mandatory.

**Comment by nils-work** [comment]
A fix for this issue has been staged for review, linked with the details provided in this issue comment - https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/599#issuecomment-1715159349

**Comment by nils-work** [comment]
This change has been incorporated into version 1.27.0
