### ISSUE TITLE
Separate Archives

### ISSUE THREAD

**Issue by JamesMBligh** [ConsumerDataStandardsAustralia/standards-staging#65]
**Description**
Feedback from the community indicates that the inclusion of built files for archived versions of the standards creates issues for understanding differences between versions when doing a diff.

**Related Work Items**
Separate out the archived build versions of the standards so they can still be made available to community for looking at the history but so they don't need to be included in the main repositories

**Options**
1. Separate archives into a separate repo and publish using pages on a different base path
2. Build older versions and commit them in the docs/archive folder in the branch of the main repository that will be used by GitHub pages

**Comment by JamesMBligh** [comment]
An archives repository containing only the built archive files has been created and the archive links in the draft of release 1.15.0 has been modified to connect to this repository.  This a trial and, if no negative feedback is received, it will be incorporated in the 1.15.0 release.

To review you can see the modified links at: https://consumerdatastandardsaustralia.github.io/standards-staging/#archives

We have received feedback in the past that we have a lot of different repositories and this can create confusion.  To offset this the archive repository is private since all of the content is publicly available in the history of the main standards repository.  While the repository is private the static files that are published via GitHub Pages are visible publicly and can be accessed via the links in release 1.15.0.

**Comment by perlboy** [comment]
Moving archives to a separate repository serves no purpose other than fragmenting the standards further _especially_ since this new repository is private. There is already a solution for this in the Git landscape called tags which serves exactly the same purpose, for instance [v1.13.0](https://github.com/ConsumerDataStandardsAustralia/standards/tree/release/1.13.0/docs) and this is what was suggested.

This solution does not follow any norm and appears to be the inverse of what has been suggested. Consequently I, a member of the community, oppose it.
